server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /etc/promtail/positions.yaml

clients:
  - url: "${LOKI_ADDRESS}/loki/api/v1/push"

scrape_configs:
- job_name: "${SERVER_NAME}_default"
  static_configs:
  - targets:
      - localhost
    labels:
      job: "${SERVER_NAME}_default_log"
      __path__: /home/ubuntu/backend/logs/production/default/default.log/

- job_name: "${SERVER_NAME}_warn-error"
  static_configs:
  - targets:
      - localhost
    labels:
      job: "${SERVER_NAME}_warn-error_log"
      __path__: /home/ubuntu/backend/logs/production/warn-error/warn-error.log/

- job_name: "${SERVER_NAME}_http"
  static_configs:
  - targets:
      - localhost
    labels:
      job: "${SERVER_NAME}_http_log"
      __path__: /home/ubuntu/backend/logs/production/http/http.log/
